### ISSUE TITLE
HapMap example error

### ISSUE THREAD

**Issue by agladstein** [agladstein/SimPrily#71]
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ~/simprily_env/bin/python simprily.py -p examples/real_data_egs/eg1/param_file_HapMap.txt -m examples/real_data_egs/eg1/model_file_HapMap.csv -i hapmap_test -o output_dir
JOB hapmap_test
Current Seed: 15957
Traceback (most recent call last):
  File "simprily.py", line 219, in <module>
    main(argv)
  File "simprily.py", line 38, in main
    processedData = process_input_files(args['param file'], args['model file'], args)
  File "/vagrant/processInput.py", line 634, in process_input_files
    model_params_variables = define_priors(model_params_dict_raw, model_data_raw)
  File "/vagrant/processInput.py", line 291, in define_priors
    model_params_dict = define_time_priors(model_params_dict, model_data_raw)
  File "/vagrant/processInput.py", line 252, in define_time_priors
    time_data = get_time_data(flag, model_params_dict_raw, time_data_raw, timed_flags)
  File "/vagrant/processInput.py", line 273, in get_time_data
    time_data = process_time_data(flag, last_time_value, model_params_dict_raw, time_data_raw)
  File "/vagrant/processInput.py", line 164, in process_time_data
    temp_time = str(float(last_time) + 1)
ValueError: could not convert string to float: ' TEU_AS'
```

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ~/simprily_env/bin/python real_data_ss.py -p examples/real_data_egs/eg1/param_file_HapMap.txt -m examples/real_data_egs/eg1/model_file_HapMap.csv -o output_dir -g test_10_YRI_CEU_CHB.tped -a test_10_YRI_CEU_CHB_KHV_hg18_ill_650.tped
Current Seed: 1132
Traceback (most recent call last):
  File "real_data_ss.py", line 142, in <module>
    main(argv)
  File "real_data_ss.py", line 54, in main
    processedData =  process_input_files(param_file, model_file, args)
  File "/vagrant/processInput.py", line 634, in process_input_files
    model_params_variables = define_priors(model_params_dict_raw, model_data_raw)
  File "/vagrant/processInput.py", line 291, in define_priors
    model_params_dict = define_time_priors(model_params_dict, model_data_raw)
  File "/vagrant/processInput.py", line 252, in define_time_priors
    time_data = get_time_data(flag, model_params_dict_raw, time_data_raw, timed_flags)
  File "/vagrant/processInput.py", line 273, in get_time_data
    time_data = process_time_data(flag, last_time_value, model_params_dict_raw, time_data_raw)
  File "/vagrant/processInput.py", line 164, in process_time_data
    temp_time = str(float(last_time) + 1)
ValueError: could not convert string to float: ' TEU_AS'
```

**Comment by agladstein** [comment]
https://github.com/agladstein/SimPrily/commit/5bcc2f46542f71b8a0fa187ff608642062847fc0
